import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body   suppressHydrationWarning={true}  className={inter.className}>
      <div className='h-screen overflow-x-hidden'>
      {/* <Navbar/> */}
      {children}
      <div className='base:mt-28 mt-8 w-full 2xl:h-[40rem] md_link:h-[25rem] h-[10rem] bg-blue-600  md_link:px-20 px-10 md_link:pt-20 pt-10'>
                <div className=' bg-chat_bg bg-no-repeat bg-cover h-full w-full rounded-t-xl '></div>
            </div>
    <Footer/>
      </div>
     
      </body>
    </html>
  )
}
